# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lavanya rajeswari/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/lavanya rajeswari/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lavanya rajeswari/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and

#### 3. Create a null vector of size 10

In [4]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
print(arr.size*arr.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
np.add?


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [10]:
arr1=np.arange(10,49)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [11]:
print(arr1[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
arr2=np.arange(0,9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [13]:
arr3=np.array([1,2,0,0,4,0])
print(np.nonzero(arr3))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [14]:
arr4=np.eye(3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [17]:
arr5=np.random.random((3,3,3))
print(arr5)

[[[0.23387785 0.53070692 0.89165464]
  [0.82938632 0.01074271 0.97776827]
  [0.0229154  0.85643354 0.21836611]]

 [[0.53291823 0.90084169 0.07360051]
  [0.13293075 0.23787018 0.61775149]
  [0.75787103 0.14718347 0.45035111]]

 [[0.99149352 0.69643895 0.16884188]
  [0.1003117  0.09210384 0.9071601 ]
  [0.77993941 0.01351042 0.32513821]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
arr6=np.random.random((10,10))
print(np.max(arr6))
print(np.min(arr6))

0.9991661729885192
0.005875512949966466


#### 14. Create a random vector of size 30 and find the mean value

In [22]:
arr7=np.random.random(30)
print(np.mean(arr7))

0.5355878085550221


#### 15. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr8=np.ones((4,4))
arr8[1:-1,1:-1]=0
print(arr8)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [29]:
arr8 = np.pad(arr8, pad_width=1, mode='constant', constant_values=0)
print(arr8)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [31]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
arr9=np.diag([1,2,3,4])
print(arr9)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [36]:
arr10=np.zeros((8,8),dtype=int)
arr10[1::2,1::2]=1
arr10[0::2,0::2]=1
print(arr10)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
